---
  - name: "Create software directory under root homedir, if it does not exist"
    file:
      path: "/root/software/{{ package_name.split('.')[0] }}/"
      state: directory

  - name: "Download and unzip Rapid7 Insight agent software package from local repository"
    unarchive:
      src: "{{ software_url }}/{{ package_name }}"
      dest: "/root/software/{{ package_name.split('.')[0] }}/"
      remote_src: yes

  - name: "Change the execute permissions of the installer script"
    file:
      path: "/root/software/{{ package_name.split('.')[0] }}/agent_installer.sh"
      owner: root
      group: root
      mode: 0777

  - name: "Install Rapid7 Insight agent"
    block:
      - name: "Run agent_installer.sh script to install the Insight agent (Token Based)"
        command: ./agent_installer.sh install_start --token {{ regionalID|quote }}:{{ UUID|quote }}
        args:
          chdir: "/root/software/{{ package_name.split('.')[0] }}/"
          creates: /opt/rapid7/ir_agent/ir_agent
        when: token_install|bool == True
        notify: restart service

      - name: "Run agent_installer.sh script to install the Insight agent (Certificate Based)"
        command: ./agent_installer.sh install_start
        args:
          chdir: "/root/software/{{ package_name.split('.')[0] }}/"
          creates: /opt/rapid7/ir_agent/ir_agent
        when: token_install|bool == False
        notify: restart service
    when: install|bool == True

  - name: "Uninstall Rapid7 Insight agent"
    block:
      - name: "Run agent_installer.sh script to uninstall the Insight agent"
        command: ./agent_installer.sh uninstall
        args:
          chdir: "/root/software/{{ package_name.split('.')[0] }}/"
          creates: /opt/rapid7/ir_agent/ir_agent
    when: uninstall|bool == True
