---
  - name: "Gather the package facts"
    ansible.builtin.package_facts:
      manager: auto
    when: ansible_facts.packages is not defined

  - name: "Install required packages"
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
      - unzip
    when: item|string not in ansible_facts.packages

  - name: "Create software directory under root homedir, if it does not exist"
    ansible.builtin.file:
      path: "/root/software/rapid7-agent/"
      state: directory

  - name: "Download and unzip Rapid7 Insight agent software package from local repository"
    ansible.builtin.unarchive:
      src: "{{ software_url }}/{{ package_name }}"
      dest: "/root/software/rapid7-agent/"
      remote_src: yes

  - name: "Change the execute permissions of the installer script"
    ansible.builtin.file:
      path: "/root/software/rapid7-agent/agent_installer.sh"
      owner: root
      group: root
      mode: '0770'

  - name: "Run agent_installer.sh script to install the Insight agent (Token Based)"
    command: ./agent_installer.sh install_start --token {{ regionalID|quote }}:{{ UUID|quote }} --https-proxy={{ location_proxy_host }}:{{ location_proxy_port }}
    args:
      chdir: "/root/software/rapid7-agent/"
      creates: /opt/rapid7/ir_agent/ir_agent
    notify: restart service
    when:
      - token_install|bool == True
      - install|bool == True

  - name: "Run agent_installer.sh script to install the Insight agent (Certificate Based)"
    command: ./agent_installer.sh install_start --https-proxy={{ location_proxy_host }}:{{ location_proxy_port }}
    args:
      chdir: "/root/software/rapid7-agent/"
      creates: /opt/rapid7/ir_agent/ir_agent
    notify: restart service
    when:
      - token_install|bool == False
      - install|bool == True

  - name: "Uninstall Rapid7 Insight agent"
    block:
      - name: "Run agent_installer.sh script to uninstall the Insight agent"
        command: ./agent_installer.sh uninstall
        args:
          chdir: "/root/software/rapid7-agent/"
    when: install|bool == False
